services:
  client:
    build:
      context: ./client
    container_name: client_container
    ports:
      - "4173:4173"
    expose:
      - "4173"
    command: >
      sh -c "npm run preview -- --host"

  server:
    build:
      context: ./server
    container_name: server_container
    ports:
      - "3000:3000"
    expose:
      - "3000"
    command: >
      sh -c "node index.js"